#!/bin/bash

cd $(dirname $0)

ANYDIR=$(pwd)
ICODIR=$(echo ${ANYDIR#*/} | tr '/' ':')
DEFAULT_KBD_LAYOUTS="Russian Colemak"

VPNUSER=$(test -e auth && head -1 auth)
if [ -z "${VPNUSER}" ]; then
  result=$(osascript -e "display dialog \"VPN username:\" with title \"AnyVPN\" with icon file \"${ICODIR}:user.png\" default answer \"\" buttons {\"Cancel\", \"Continue\"} default button \"Continue\"")

  if echo $result | grep Continue; then
    VPNUSER=$(echo $result | cut -d: -f3)
  else
    exit
  fi
fi

VPNPASS=$(test -e auth && sed -n '2p' auth)
if [ -z "$VPNPASS" ]; then
  xkbswitch-macosx/bin/xkbswitch -se US

  result=$(osascript -e "display dialog \"VPN password:\" with title \"AnyVPN\" with icon file \"${ICODIR}:pass.png\" default answer \"\" buttons {\"Cancel\", \"Continue\"} default button \"Continue\" with hidden answer")

  for name in "$DEFAULT_KBD_LAYOUTS"; do xkbswitch-macosx/bin/xkbswitch -se $name; done

  if echo $result | grep Continue; then
    VPNPASS=$(echo $result | cut -d: -f3)
  else
    exit
  fi
fi

sudo /usr/local/opt/openvpn/sbin/openvpn \
  --config $ANYDIR/config.ovpn \
  --script-security 2 \
  --daemon \
  --log $ANYDIR/openvpn.log \
  --route-up $ANYDIR/up \
  --down $ANYDIR/down \
  --auth-user-pass \
  --management-query-passwords \
  --management $ANYDIR/socket unix

echo "username Auth $VPNUSER" | nc -U socket
echo "password Auth $VPNPASS" | nc -U socket

touch connected
